#! /bin/bash

# Created By Adarsh Addee
# Aim: To Access Root Privileges in Termux
# Date: 27 Aug 2021
# Note: THIS TOOL WILL NOT GIVE YOU REAL ROOT ACCESS

clear
echo -e "\e[1;31m"


echo -e "\e[0m"
mv /data/data/com.termux/files/usr/etc/bash.bashrc /data/data/com.termux/files/usr/etc/bash.bashrc_old
cp bash.bashrc /data/data/com.termux/files/usr/etc/bash.bashrc

apt-get update && apt-get upgrade -y
apt-get install fish  ncurses-utils proot proot-distro tsu fakeroot parted -y

clear

echo -e "\e[1;31m"
echo " ██▀███      ▒█████      ▒█████     ▄▄▄█████▓"
echo "▓██ ▒ ██▒   ▒██▒  ██▒   ▒██▒  ██▒   ▓  ██▒ ▓▒"
echo "▓██ ░▄█ ▒   ▒██░  ██▒   ▒██░  ██▒   ▒ ▓██░ ▒░"
echo "▒██▀▀█▄     ▒██   ██░   ▒██   ██░   ░ ▓██▓ ░ "
echo "░██▓ ▒██▒   ░ ████▓▒░   ░ ████▓▒░     ▒██▒ ░ "
echo "░ ▒▓ ░▒▓░   ░ ▒░▒░▒░    ░ ▒░▒░▒░      ▒ ░░   "
echo "  ░▒ ░ ▒░     ░ ▒ ▒░      ░ ▒ ▒░        ░    "
echo "  ░░   ░    ░ ░ ░ ▒     ░ ░ ░ ▒       ░      "
echo "   ░            ░ ░         ░ ░              "

echo -e "\e[1;36m\n"
echo "[*] Automation started"
sleep 1
echo "[*] Syncing"
sleep 0.5
echo "[*] Collecting packages"
echo "[*] Preparing files"

echo "[*] done"

sleep 1.5
echo -e "\n\n\e[0mHit ENTER to continue..."
read

clear
termux-reload-settings
echo -e "please type \e[1;32mfakeroot\e[1;34m for fakeroot\n\n"

